/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Windows8.1
 */
public class ManageProduct extends javax.swing.JFrame {

    /**
     * Creates new form ManageProject
     */
    public ManageProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        jButton3.setText("ย้อนกลับ");
        getContentPane().add(jButton3);
        jButton3.setBounds(523, 690, 80, 30);

        jButton4.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        jButton4.setText("ยืนยัน");
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 690, 70, 30);

        jButton5.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        jButton5.setText("เพิ่ม");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(140, 420, 70, 30);

        jLabel1.setFont(new java.awt.Font("supermarket", 1, 48)); // NOI18N
        jLabel1.setText("จัดการสินค้า");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 70, 220, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/catetory5.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 140, 170, 170);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/catetory2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 140, 170, 170);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/catetory4.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(820, 140, 170, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/catetory.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 140, 170, 170);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/bag1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 320, 170, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/bag2.png"))); // NOI18N
        jLabel12.setText("jLabel10");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(420, 320, 170, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/ba4.png"))); // NOI18N
        jLabel13.setText("jLabel10");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(620, 320, 170, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/bag3.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(820, 320, 170, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/magnifier (1).png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 360, 41, 40);

        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/man-user.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1100, 20, 30, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/logout.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1150, 20, 40, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(870, 20, 210, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 360, 770, 40);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 420, 770, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/Untitled-1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
