package GUI;

import model.Customer;


public class ViewUser extends javax.swing.JFrame {
    private Customer ct;
    
    public ViewUser(Customer ct) {
        this.ct = ct;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("supermarket", 1, 48)); // NOI18N
        jLabel1.setText("ข้อมูลส่วนตัว");
        jLabel1.setMaximumSize(new java.awt.Dimension(340, 58));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 50, 260, 58);

        jLabel16.setFont(new java.awt.Font("supermarket", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText(ct.getFirstname()+" "+ct.getLastname());
        getContentPane().add(jLabel16);
        jLabel16.setBounds(600, 20, 190, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/system/man-user.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 10, 30, 40);

        jLabel9.setFont(new java.awt.Font("supermarket", 1, 22)); // NOI18N
        jLabel9.setText("เบอร์โทรศัพท์");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 290, 110, 40);

        jLabel10.setFont(new java.awt.Font("supermarket", 1, 22)); // NOI18N
        jLabel10.setText("นามสกุล");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 120, 70, 40);

        jLabel11.setFont(new java.awt.Font("supermarket", 1, 22)); // NOI18N
        jLabel11.setText("ที่อยู่");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 170, 40, 30);

        jLabel12.setFont(new java.awt.Font("supermarket", 1, 22)); // NOI18N
        jLabel12.setText("e-mail");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 290, 60, 40);

        jLabel4.setFont(new java.awt.Font("supermarket", 1, 22)); // NOI18N
        jLabel4.setText("หมายเลขคนแนะนำ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 350, 150, 40);

        jButton1.setText("ยืนยัน");
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 420, 100, 30);

        jButton2.setText("ย้อนกลับ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 420, 100, 30);

        jLabel15.setFont(new java.awt.Font("supermarket", 1, 22)); // NOI18N
        jLabel15.setText("ชื่อ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(100, 120, 40, 40);

        jTextField1.setText(ct.getTelNo());
        getContentPane().add(jTextField1);
        jTextField1.setBounds(540, 290, 200, 40);

        jTextField2.setText(ct.getFirstname());
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 120, 250, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(ct.getAddress());
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 170, 590, 110);

        jTextField3.setText(ct.getLastname());
        getContentPane().add(jTextField3);
        jTextField3.setBounds(490, 120, 250, 40);

        jTextField4.setText(ct.getEmail());
        getContentPane().add(jTextField4);
        jTextField4.setBounds(150, 290, 250, 40);

        jTextField5.setText(ct.getCustomerInviteNo()+"");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(230, 350, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        News n = new News(ct);
        n.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
